# Generated by Django 3.2.4 on 2023-02-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='grandtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='shipping',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
