# Generated by Django 3.2.4 on 2023-02-04 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230204_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('unitprice', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('dtotal', models.IntegerField()),
                ('dorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ordermodel')),
            ],
        ),
    ]
